connections:
  ia_demo:
    user: IA_DEV_BI_USER
    account: A5680544785571-TX50041
    warehouse: IA_DEV_BI_WH
    database: IA_DEMO
    schema: PUBLIC
    role: IA_DEV_BI_ROLE
    authenticator: SNOWFLAKE_JWT
    private_key_source: 'vault'
    vault:
      addr: 'https://vault3.intainabs.com'
      role_id: bd69c5e3-ffcb-9c5b-c418-771cde1e7476
      secret_id: 6dad5a57-9cc1-0c75-9813-70d0926d081c
      sign_path: '/v1/Snowflake/data/Credentials'
      secret_field: 'file.p8'
  ia_uat:
      user: IDA_WRITE_USER
      account: A5680544785571-TX50041
      warehouse: IA_DEV_BI_WH
      database: IA_UAT
      schema: IDA_TEST
      role: IDA_TEST_RW_ROLE
      authenticator: SNOWFLAKE_JWT
      private_key_source: 'vault'
      vault:
        addr: 'https://vault3.intainabs.com'
        role_id: bd69c5e3-ffcb-9c5b-c418-771cde1e7476
        secret_id: 6dad5a57-9cc1-0c75-9813-70d0926d081c
        sign_path: '/v1/Snowflake/data/Credentials'
        secret_field: 'ida_write_user_key'
